# config/eplan.yaml
eplan:
  installation:
    path: "C:\\Program Files\\EPLAN\\Platform\\2023.0.3\\Bin"
    version: "2023.0.3"
    variant: "Electric P8"
  
  remoting:
    host: "localhost"
    port: "49152"
    timeout: 5
    auto_start: false
  
  directories:
    output: "C:\\temp\\Agent"
    logs: "C:\\temp\\Agent\\EplanLog"
    scripts: "C:\\temp\\Agent"
  
  files:
    script_name: "eplan_script.cs"
    log_file: "Events.csv"
  
  actions:
    common:
      export3d: "export3d"
      reports: "reports"
      renumber: "renumber"
      export: "export"
  
  validation:
    required_attributes: ["[Start]"]
    forbidden_patterns: ["$[^(]"]  # $ not followed by (
    required_usings: ["Eplan.EplApi.ApplicationFramework"]